version: "3.8"

services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - reports_data:/app/static/reports
      - storage_data:/app/static/storage
    env_file:
      - .env
    restart: always

volumes:
  reports_data:
  storage_data:
