"""init_tables

Revision ID: c133d7fd61b6
Revises: 
Create Date: 2026-06-17 19:38:06.692907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c133d7fd61b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('client_secret', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('reset_password_token', sa.String(length=255), nullable=True),
    sa.Column('reset_password_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_attempts_ip', sa.String(length=45), nullable=True),
    sa.Column('last_device_logged', sa.String(length=255), nullable=True),
    sa.Column('last_ip_logged', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_email'), 'admin', ['email'], unique=True)
    op.create_index(op.f('ix_admin_id'), 'admin', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('birth_time', sa.Time(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('birth_city', sa.String(length=250), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('stripe_session_id', sa.String(length=255), nullable=True),
    sa.Column('plan_type', sa.Enum('ESSENTIEL', 'COMPLET', 'ANNEE_COSMIQUE', 'COSMOS_INTEGRAL', name='plan_type_enum'), nullable=True),
    sa.Column('status', sa.Enum('PENDING_PAYMENT', 'PAID', 'PROCESSING', 'COMPLETED', 'FAILED', name='order_status_enum'), nullable=True),
    sa.Column('amount_total', sa.Integer(), nullable=False),
    sa.Column('has_audio', sa.Boolean(), nullable=False),
    sa.Column('has_poster', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_email'), 'orders', ['email'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_stripe_session_id'), 'orders', ['stripe_session_id'], unique=True)
    op.create_table('astrological_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('astral_data_json', sa.JSON(), nullable=True),
    sa.Column('ai_content_json', sa.JSON(), nullable=True),
    sa.Column('pdf_url', sa.String(length=512), nullable=True),
    sa.Column('pdf_name', sa.String(length=255), nullable=True),
    sa.Column('audio_url', sa.String(length=512), nullable=True),
    sa.Column('poster_url', sa.String(length=512), nullable=True),
    sa.Column('generation_duration', sa.Float(), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index(op.f('ix_astrological_reports_id'), 'astrological_reports', ['id'], unique=False)
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('token_type', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_id'), 'tokens', ['id'], unique=False)
    op.create_index(op.f('ix_tokens_token_hash'), 'tokens', ['token_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokens_token_hash'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_id'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_index(op.f('ix_astrological_reports_id'), table_name='astrological_reports')
    op.drop_table('astrological_reports')
    op.drop_index(op.f('ix_orders_stripe_session_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_email'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_admin_id'), table_name='admin')
    op.drop_index(op.f('ix_admin_email'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
